export const topics = {
    Ransomware: [
        'Random',
        'Types of ransomware',
        'Ransomware distribution methods',
        'Ransomware infection vectors',
        'Ransomware payloads',
        'Ransomware encryption techniques',
        'Ransomware decryption methods',
        'Ransomware payment mechanisms',
        'Ransomware negotiation tactics',
        'Ransomware prevention strategies',
        'Ransomware detection techniques',
        'Ransomware incident response',
        'Ransomware impact assessment',
        'Ransomware legal implications',
        'Ransomware recovery methods',
        'Ransomware forensics',
        'Ransomware evolution and trends',
        'Ransomware mitigation techniques',
    ],
    cryptography: [
        'Random',
        'Encryption algorithms',
        'Decryption algorithms',
        'Symmetric cryptography',
        'Asymmetric cryptography',
        'Key management',
        'Cryptographic hashing',
        'Digital signatures',
        'Public key infrastructure (PKI)',
        'Cryptographic protocols',
        'Cryptanalysis techniques',
        'Cryptographic attacks',
        'Secure communication protocols',
        'Blockchain and cryptography',
        'Quantum cryptography',
        'Homomorphic encryption',
    ],
    AppSec: [
        'Random',
        'Web Application Firewalls (WAF)',
        'Cross-Site Scripting (XSS)',
        'SQL Injection',
        'Cross-Site Request Forgery (CSRF)',
        'Session Management',
        'Authentication and Authorization',
        'Input Validation',
        'Output Encoding',
        'Secure Coding Practices',
        'Security Headers',
        'Content Security Policy (CSP)',
        'Clickjacking',
        'File Upload Security',
        'Secure Development Lifecycle (SDL)',
        'Web Application Penetration Testing',
        'Web Application Security Scanners',
        'Security Misconfiguration',
        'Broken Authentication',
        'Sensitive Data Exposure',
        'Insecure Deserialization',
        ],
    Network: [
        'Random',
        'Firewalls',
        'Intrusion Detection Systems (IDS)',
        'Intrusion Prevention Systems (IPS)',
        'Network Access Control (NAC)',
        'Virtual Private Networks (VPNs)',
        'Network Segmentation',
        'Denial of Service (DoS) attacks',
        'Distributed Denial of Service (DDoS) attacks',
        'Network Traffic Analysis',
        'Packet Sniffing',
        'Port Scanning',
        'Network Security Protocols',
        'Secure Socket Layer (SSL) / Transport Layer Security (TLS)',
        'Network Authentication Protocols',
        'Wireless Security (Wi-Fi security)',
        'Network Forensics',
        'Network Security Policies',
        'Security Information and Event Management (SIEM)',
        'Security Incident Response',
        'Network Security Best Practices',
        ],
}
